Feature/lista studenti
732PC/ProiectColectiv732 pull request #12
Opened 2023-11-28 12:47 UTC by Razvan-Joita

2023-11-28 16:26 UTC, DragosPetri commented
Tests fail in CI pipeline

2023-11-28 16:31 UTC, Piciorus requested changes

2023-11-28 16:31 UTC, Piciorus commented on src/main/UI/modificareStudent.html
> +<!-----------Delete--------------------------->
you can remove comment code

2023-11-28 16:31 UTC, Piciorus commented on src/main/UI/script.js
> +// const studentDataList = [
remove if it is not used

2023-11-28 16:31 UTC, Piciorus commented on src/main/UI/style.css
> +/*
comment code?

2023-11-28 16:31 UTC, Piciorus commented on src/main/java/org/example/Main.java
> +
remove empty line

2023-11-28 16:31 UTC, Piciorus commented on src/main/java/org/example/controllers/StudentController.java
> +//    @PostMapping
do we need this code?

2023-11-28 16:31 UTC, Piciorus commented on src/main/resources/application.properties
> +spring.datasource.username=root
why you changed the credentials for datasource?

2023-11-28 16:52 UTC, Kl3igrec commented on src/main/UI/style.css
> +/*#student-list {*/
Remove it if you don't use it 🍡

2023-11-28 16:53 UTC, Kl3igrec commented on src/main/java/org/example/controllers/StudentController.java
> +    @PostMapping(value = "/addStudent")
This isn't restful, remove /addStudent

2023-11-28 16:54 UTC, Kl3igrec commented on src/main/java/org/example/controllers/StudentController.java
> +
Empty lines ?

2023-11-28 16:55 UTC, Kl3igrec commented on src/main/java/org/example/services/StudentService.java
> +    public List<Students> getAllStudents() {
Please make a Paginated Get <3

2023-11-28 16:55 UTC, Kl3igrec commented on src/main/java/org/example/services/StudentService.java
> +            // Use setters directly for brevity
?????

2023-11-28 16:57 UTC, Kl3igrec commented on src/main/java/org/example/services/StudentService.java
> +        if (isValidCnpLength(student.getCnp())) {
SOLID ? Please move this into a different method

2023-11-28 17:01 UTC, Kl3igrec commented on src/main/java/org/example/controllers/StudentController.java
> +    private boolean isValidCnpLength(String cnp) {
Are you using this?

2023-12-04 10:54 UTC, DragosPetri requested changes
Fix tests.

2023-12-04 12:33 UTC, closed without merging