Feature/confirmare creare cont
732PC/ProiectColectiv732 pull request #16
Opened 2023-12-01 20:51 UTC by aairina

2023-12-04 10:47 UTC, Piciorus requested changes

2023-12-04 10:47 UTC, Piciorus commented on src/main/java/org/example/controller/UserController.java
> +                    "src/main/java/org/example/service/emailTemplateAccountConfirmation.txt",
can you find a way to no define the entire path to txt file?

2023-12-04 17:08 UTC, Piciorus commented
i think you should add tests for mail service

2023-12-05 06:57 UTC, Piciorus approved these changes

2023-12-12 15:40 UTC, VladP2002 approved these changes

2023-12-12 16:14 UTC, merged