Feature/alocare automata cursuri studenti
732PC/ProiectColectiv732 pull request #19
Opened 2023-12-03 21:18 UTC by Lordsib

2023-12-04 10:43 UTC, Piciorus requested changes

2023-12-04 10:43 UTC, Piciorus commented on src/main/java/org/example/Controller/CourseAllocationController.java
> +//     /   return ResponseEntity.ok("Courses assigned automatically based on current study year");
?

2023-12-04 10:43 UTC, Piciorus commented on index.html
> +        .header {
add this in a separat css file

2023-12-04 10:43 UTC, Piciorus commented on index.html
> +    </div>
add this to a different  html file assing courses?

2023-12-04 10:43 UTC, Piciorus commented on pom.xml
> +        <dependency>
sync with dev ... those dependencies exist

2023-12-04 17:12 UTC, Piciorus commented
please add a print screen to see how it looks like

2023-12-05 16:30 UTC, Lordsib commented
[Course Allocation.pdf](https://github.com/732PC/ProiectColectiv732/files/13562756/Course.Allocation.pdf)

2023-12-05 16:30 UTC, closed without merging

2023-12-05 16:31 UTC, Lordsib commented on index.html
> +    </div>
I don't understand. I added that to look like the mock up. It's not my job

2023-12-06 19:34 UTC, Piciorus commented on index.html
> +    </div>
you could move this to a different file and to call it here in index..also you should merge in develop...not in main